name: ilac_dolabi
description: Ev ilaç envanteri - karekod okuyucu
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: 5.2.3       # karekod / DataMatrix okuma (sürüm sabit)
  image_picker: 1.1.2         # telefonun kamerasıyla fotoğraf çekme
  shared_preferences: ^2.3.2  # ilaçları telefonda kalıcı saklama

flutter:
  uses-material-design: true
